# Generated by Django 4.2.9 on 2024-02-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('C', 'Создан'), ('A', 'Принят'), ('D', 'Отклонен')], default='C', max_length=1),
        ),
    ]
